- name: add required packages
  yum:
    name:
      - python3-pip
    state: present
  become: yes

- name: upgrade pip package
  pip: 
    name: pip
    extra_args: --upgrade

- name: install kubernetes python tools
  pip:
    name: 
      - kubernetes
      - kubernetes-validate
      - cryptography
  become: yes