---
# tasks file for setup-bootpxe
- name: install required packages
  yum:
    name:
      - jq
      - ipmitool
      - httpd
      - dhcp-server
      - tftp-server
    state: present
  become: yes

- name: Setup networking
  include: network.yml
  tags: network,deps

- name: setup TFTP server
  include: tftpd.yml
  tags: tftpd,deps

- name: setup HTTP server
  include: http.yml
  tags: http,deps
