---
# tasks file for setup-bootpxe
- name: Testing variable's 
  assert:
    that:
      - INTERFACE is defined
      - INTERFACE != ""
    fail_msg: "variable 'INTERFACE' must be defined"
    success_msg: "Pass"

- name: install required packages
  yum:
    name:
      - jq
      - ipmitool
      - httpd
      - dhcp-server
      - tftp-server
    state: present
  become: yes

- name: Ensure Python tools installed
  pip:
    name: netaddr
  delegate_to: localhost

- name: Setup networking
  include_tasks: network.yml
  tags: network,deps

- name: setup TFTP server
  include_tasks: tftpd.yml
  tags: tftpd,deps

- name: setup HTTP server
  include_tasks: http.yml
  tags: http,deps
